openapi: "3.0.0"
info:
  version: 1.0.0
  title: Find eat price
  description: side project
  contact:
    name: "damody"
    url: "https://www.facebook.com/Remake.AON/"
    email: "t1238142000@gmail.com"
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
servers:
  - url: https://find-eat-price.com/v1
paths:
  /restaurants/search:
    $ref: /paths/restaurants/search.yaml
  /restaurants/show/{restaurantId}:
    $ref: /paths/restaurants/show.yaml
  /foods/search:
    $ref: /paths/foods/search.yaml
  /foods/show/{restaurantId}:
    $ref: /paths/foods/show.yaml