openapi: "3.0.0"
info:
  version: 0.1
  title: Find eat price
  description: side project
  contact:
    name: "damody"
    url: "https://www.facebook.com/Remake.AON/"
    email: "t1238142000@gmail.com"
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
servers:
  - url: http://127.0.0.1:8080/
paths:
  /restaurant:
    $ref: /paths/restaurant/edit.yaml
  /restaurant/search:
    $ref: /paths/restaurant/search.yaml
  /restaurant/{restaurantId}:
    $ref: /paths/restaurant/get.yaml
  /restaurant/like:
    $ref: /paths/restaurant/like.yaml

  /food:
    $ref: /paths/food/edit.yaml
  /food/search:
    $ref: /paths/food/search.yaml
  /food/menu:
    $ref: /paths/food/menu.yaml
  /food/{foodId}:
    $ref: /paths/food/get.yaml
  /food/{foodId}/comment:
    $ref: /paths/food/comment.yaml
  /food/like:
    $ref: /paths/food/like.yaml
  
  /member:
    $ref: /paths/member/edit.yaml
  /member/{memberId}:
    $ref: /paths/member/get.yaml
  /member/{memberId}/comment:
    $ref: /paths/member/comment.yaml
  
  /comment:
    $ref: /paths/comment/edit.yaml
  /comment/{commentId}:
    $ref: /paths/comment/get.yaml
  /comment/like:
    $ref: /paths/comment/like.yaml
  /comment/array:
    $ref: /paths/comment/array.yaml